- name: demo on loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}" # item is reserved keyword
    loop:
    - yamuna
    - Raj
    - Sumi